import time

words = ['farts uh oh....STINKY!!', 'POOP!!!!!!!', 'AHAHAHAHAHAHHHAHAHHAHHAHAHAHH FUNNY POOPIES!!!!!!!!!!!', 'XD ELELELELELELELEL PPPPPPPOOOOO', 'PPPPPPPPPPYYYYYYYYYYY', 'YYYYYYYYYYYYYYYYYYYYY','YYY!!!!!!!!!!!!!!!!! HAHAHAH AHAHAH', 'AHAHAHA FUNNY POOP! POOP FUNNY! WEE', 'EEEEEEEEEEEEEEE!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! YAY FOR POOPIE! GOOD POOPIE! POOPIE FUNNY! AHAH XDDD', 'DDDDDDD', 'DDDDDDD DDDDD POOP POOP POOP POOP POOP POOP POOP POOP POOP', 'POOP POOP POOP POOP POOP POOP POOP POOP POOP', 'POOP POOP POOP POOP POOP POOP POOP POOP POOP POOP POOP POOP POOP POOP POOP POOP POOP POOP', 'POOP POOP POOP POOP POOP POOP POOP POOP POOP LELELELELELELELELELELELLE XDXDXD', 'POOPY FUNNY! YAY! FUN FUN POOP', '! TEE HEE XD POOP! POOPY! YAY! POOP MAKE ME HAPPY! HAPPY HAPPY P', 'OOP POOP! AHAHAHAHAHAHAHHAHAHAHHAHAHAHHAHHAHDXDXD']

for word in words:
    time.sleep(2)
    print(word)
    print('')